version: "3"
services:
  validate:
    # must be run in conjunction with the docker-compose stack.
    image: node:12.18.0
    network_mode: "service:shim"
    entrypoint: [ "./localAPI/wait-for-dashboard.sh", "npm", "run", "validate"]
    working_dir:
      /cumulus-dashboard
    volumes:
      - ../:/cumulus-dashboard:cached
    environment:
      - CYPRESS_TESTING=true
      - NODE_ENV=test
      - LOCALSTACK_HOST=localhost
      - LOCAL_ES_HOST=localhost
